### ISSUE TITLE
CUDA memory issue during inference

### ISSUE THREAD

**Issue by godhj93** [rpmsnu/sRGB-TIR#5]
Hi, When I try to run your inference code as follows the error happens as follows:
```
python3 inference_batch.py --input_folder ../data/Train/images --output_folder output --checkpoint ./translation_weights.pt --a2b 0 --seed 123 --num_style 1 --synchronized --output_only --config configs/tir2rgb_folder_unit.yaml 
../data/Train/images/0000001_02999_d_0000005.jpg
/home/hj/Projects/etri2023/sRGB-TIR/inference_batch.py:101: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  images = Variable(images.cuda(), volatile=True)
../data/Train/images/0000001_03499_d_0000006.jpg
Traceback (most recent call last):
  File "/home/hj/Projects/etri2023/sRGB-TIR/inference_batch.py", line 102, in <module>
    content, _ = encode(images)
  File "/home/hj/Projects/etri2023/sRGB-TIR/networks.py", line 120, in encode
    content = self.enc_content(images)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hj/Projects/etri2023/sRGB-TIR/networks.py", line 221, in forward
    return self.model(x)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hj/Projects/etri2023/sRGB-TIR/networks.py", line 254, in forward
    return self.model(x)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hj/Projects/etri2023/sRGB-TIR/networks.py", line 284, in forward
    out = self.model(x)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hj/Projects/etri2023/sRGB-TIR/networks.py", line 342, in forward
    x = self.conv(self.pad(x))
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/hj/anaconda3/envs/etri/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 23.70 GiB total capacity; 21.79 GiB already allocated; 12.75 MiB free; 22.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

my environment setup is
CPU: Intel i9-10900K
RAM: 128GB
GPU: RTX3090
torch: 1.12.1
python: 3.10.11

how can I run the code? 

Thanks

**Comment by godhj93** [comment]
Thanks! It works!

**Comment by JiatengSun** [comment]
with every image under the resolution of 640x512, inference always runs out of memory after 2 images. how can i fix this?
`CUDA out of memory. Tried to allocate 148.00 MiB (GPU 0; 10.76 GiB total capacity; 8.84 GiB already allocated; 51.62 MiB free; 9.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CON`

**Comment by donkeymouse** [comment]
Hey Jiateng, 

How many style latents are you using? (the style latent here refers to --num_style flag in the argparse). 

If you are trying to translate too many number of styles, it may cause CUDA OOM issue even with smaller resolution. Can you try again with perhaps a smaller number of styles?

**Comment by JiatengSun** [comment]
this is what im running:
`python3 inference_batch.py --input_folder ./rgb --output_folder ./output --checkpoint ./translation_weights.pt --a2b 0 --seed 1234 --num_style 1 --synchronized --config configs/tir2rgb_folder.yaml'

**Comment by JiatengSun** [comment]
> Hey Jiateng,
> 
> How many style latents are you using? (the style latent here refers to --num_style flag in the argparse).
> 
> If you are trying to translate too many number of styles, it may cause CUDA OOM issue even with smaller resolution. Can you try again with perhaps a smaller number of styles?

this is what im running:
`python3 inference_batch.py --input_folder ./rgb --output_folder ./output --checkpoint ./translation_weights.pt --a2b 0 --seed 1234 --num_style 1 --synchronized --config configs/tir2rgb_folder.yaml `

**Comment by Pdash99** [comment]
I am facing the same issue for 2 input images of size 640x512. I have 2 RTX 4090s and I am still facing this issue with CUDA
